### PR TITLE
Fixed Missing Preview (My Fault)

### PR DESCRIPTION
**Pull request by jnvoigt**
I made a little mistake.

To be honest i dont understand why the view forces me to use ReadLineAsync in order to work, when i force it to be synchrone with await anyway.

### CODE REVIEW

**Comment by aschearer** [comment]
Will merge in shortly -- I noticed the problem myself and have some local changes which seem to fix things but in a different way. One more question, running the tests I found them to fail. Changing the asserts from 21 to 2.1 appeared to fix things. Are they passing for you?

**Comment by jnvoigt** [comment]
jep thats a parsing error between the different cultures. I suggest to editg the resources to natural numbers.
The example in the Resources uses '.'-Separated Decimal but I use a German System so the parsing looks for ','-Separated Decimals

**Comment by aschearer** [comment]
OK, I have fixed conflicts and merged this into my repo. I'm going to have a look at the test case and then try to fix issue #7.

**Comment by aschearer** [comment]
For the test case, are the numbers in your Unity log file formatted for your culture? E.g. "2,1" instead of "2.1"? If they are culture invariant I will just update the parser accordingly.

**Pull request merged**
